package test

// DB-backed tests for GET /electricals/stats (electricals.Stats).
//
// The handler is deliberately thin: the payload is generated by the Laravel command
// electricals:stats and stored in electricals_stats, because every figure is a rolling
// twelve-month aggregate that is far too heavy to compute per request. So what is worth
// covering here is the serving contract - newest generation wins, the stored JSON is
// passed through unchanged, and an environment that has never generated gets a 404 rather
// than an empty object that would read as "zero electricals".

import (
	"encoding/json"
	"io"
	"net/http/httptest"
	"testing"

	"github.com/freegle/iznik-server-go/database"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func clearElectricalsStats(t *testing.T) {
	t.Helper()
	require.NoError(t, database.DBConn.Exec("DELETE FROM electricals_stats").Error)
}

func insertElectricalsStats(t *testing.T, payload string) {
	t.Helper()
	require.NoError(t, database.DBConn.Exec(
		"INSERT INTO electricals_stats (generated_at, payload) VALUES (NOW(), ?)", payload,
	).Error)
}

func fetchElectricalsStats(t *testing.T) (int, string) {
	t.Helper()

	resp, err := getApp().Test(httptest.NewRequest("GET", "/apiv2/electricals/stats", nil))
	require.NoError(t, err)

	body, err := io.ReadAll(resp.Body)
	require.NoError(t, err)

	return resp.StatusCode, string(body)
}

func TestElectricalsStats_ReturnsStoredPayload(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	insertElectricalsStats(t, `{"counts":{"electrical":42,"classified":100,"electrical_pct":42.0}}`)

	status, body := fetchElectricalsStats(t)
	assert.Equal(t, 200, status)

	var parsed map[string]interface{}
	require.NoError(t, json.Unmarshal([]byte(body), &parsed))

	counts, ok := parsed["counts"].(map[string]interface{})
	require.True(t, ok, "counts should be present")
	assert.Equal(t, float64(42), counts["electrical"])
	assert.Equal(t, float64(100), counts["classified"])
}

// The table keeps a short history so a bad generation can be compared against its
// predecessor. Only the newest may ever be served.
func TestElectricalsStats_ServesNewestGeneration(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	insertElectricalsStats(t, `{"generation":"older"}`)
	insertElectricalsStats(t, `{"generation":"newer"}`)

	status, body := fetchElectricalsStats(t)
	assert.Equal(t, 200, status)

	var parsed map[string]interface{}
	require.NoError(t, json.Unmarshal([]byte(body), &parsed))
	assert.Equal(t, "newer", parsed["generation"])
}

// A fresh environment that has never run the generator must be distinguishable from one
// whose figures are genuinely zero, so this is a 404 and not an empty object.
func TestElectricalsStats_404WhenNothingGenerated(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	status, _ := fetchElectricalsStats(t)
	assert.Equal(t, 404, status)
}

// A corrupted stored payload must be a loud 500, never served: the page would otherwise
// render from garbage, and the JSON validity check is the only guard between the two.
func TestElectricalsStats_500OnMalformedStoredPayload(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	insertElectricalsStats(t, `{"counts": truncated`)

	status, body := fetchElectricalsStats(t)
	assert.Equal(t, 500, status)
	assert.Contains(t, body, "not valid JSON")
}

// Regenerated daily, so responses carry an hour of shared caching - the only thing
// standing between a public no-args GET and the database.
func TestElectricalsStats_SetsCacheControl(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	insertElectricalsStats(t, `{"generation":"cached"}`)

	resp, err := getApp().Test(httptest.NewRequest("GET", "/apiv2/electricals/stats", nil))
	require.NoError(t, err)
	assert.Equal(t, 200, resp.StatusCode)
	assert.Equal(t, "public, max-age=3600", resp.Header.Get("Cache-Control"))
}

// The payload is stored as generated and must not be reshaped in transit: the page reads
// nested structures the handler knows nothing about.
func TestElectricalsStats_PassesNestedStructureThrough(t *testing.T) {
	clearElectricalsStats(t)
	defer clearElectricalsStats(t)

	insertElectricalsStats(t, `{"unusual":{"items":[{"name":"Bread maker","count":3}],`+
		`"guard":{"min_users":3,"min_groups":2}}}`)

	status, body := fetchElectricalsStats(t)
	assert.Equal(t, 200, status)

	var parsed struct {
		Unusual struct {
			Items []struct {
				Name  string `json:"name"`
				Count int    `json:"count"`
			} `json:"items"`
			Guard struct {
				MinUsers  int `json:"min_users"`
				MinGroups int `json:"min_groups"`
			} `json:"guard"`
		} `json:"unusual"`
	}
	require.NoError(t, json.Unmarshal([]byte(body), &parsed))

	require.Len(t, parsed.Unusual.Items, 1)
	assert.Equal(t, "Bread maker", parsed.Unusual.Items[0].Name)
	assert.Equal(t, 3, parsed.Unusual.Items[0].Count)
	assert.Equal(t, 3, parsed.Unusual.Guard.MinUsers)
	assert.Equal(t, 2, parsed.Unusual.Guard.MinGroups)
}
