package message

import (
	"encoding/json"
)

func (MessageAttachment) TableName() string {
	return "messages_attachments"
}

// MessageAttachment represents an image attached to a message.
// The ai field is true when the attachment was generated by the Freegle AI illustration service.
// Partners (e.g. TrashNothing) can use this to identify and selectively remove AI-generated images.
type MessageAttachment struct {
	ID           uint64          `json:"id" gorm:"primary_key"`
	Msgid        uint64          `json:"-"`
	Bulkitemid   *uint64         `json:"bulkitemid,omitempty"`
	Path         string          `json:"path"`
	Paththumb    string          `json:"paththumb"`
	Archived     int             `json:"archived"`
	Externaluid  string          `json:"externaluid"`
	Ouruid       string          `json:"ouruid"`
	Externalmods json.RawMessage `json:"externalmods"`
	AI           bool            `json:"ai" gorm:"-"`
	// Masked is set when the picture is a rejected/regenerating/suppressed AI illustration.
	Masked bool `json:"-" gorm:"column:masked;->"`
}

// ComputeAI populates the AI field from the externalmods JSON.
func (a *MessageAttachment) ComputeAI() {
	if len(a.Externalmods) == 0 {
		return
	}
	var m struct {
		AI interface{} `json:"ai"`
	}
	if err := json.Unmarshal(a.Externalmods, &m); err != nil {
		return
	}
	switch v := m.AI.(type) {
	case bool:
		a.AI = v
	case float64:
		a.AI = v != 0
	}
}

// dropMaskedAttachments removes attachments whose AI illustration has been masked. They have no
// externaluid, so the URL builder would otherwise point them at a legacy path that does not exist
// and clients would draw a blank photo box. With none left, clients show their no-photo placeholder.
func dropMaskedAttachments(atts []MessageAttachment) []MessageAttachment {
	kept := atts[:0]
	for _, a := range atts {
		if !a.Masked {
			kept = append(kept, a)
		}
	}
	return kept
}
