<?php

namespace App\Services;

use Carbon\Carbon;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;

/**
 * Reads apiv2's deprecated-endpoint registry (GET /deprecated) — the set of
 * routes wrapped in deprecation.Marker() plus their sunset dates — and returns
 * the ones whose sunset has passed, for monitor:deprecated-endpoints.
 *
 * The registry is served from the SAME Marker() calls that log the hits, so the
 * observed set and the logging can't drift (an observed-but-unlogged endpoint
 * would falsely read as "safe to retire"). We deliberately do NOT parse the
 * OpenAPI spec: it is generated by go-swagger, whose swagger:route form can't
 * carry an x-sunset vendor extension.
 */
class DeprecatedEndpointService
{
    /**
     * Deprecated endpoints past their sunset date — or NULL if apiv2 couldn't be
     * reached, so the caller can surface "apiv2 unreachable / misconfigured"
     * loudly instead of silently behaving like "nothing is deprecated".
     *
     * @return array<int, array{endpoint:string, sunset:string, logged_endpoint:string}>|null
     */
    public function pastSunset(Carbon $now): ?array
    {
        $list = $this->fetchRegistry();
        if ($list === null) {
            return null;
        }

        $out = [];
        foreach ($list as $entry) {
            if (! is_array($entry)) {
                continue;
            }
            $endpoint = $entry['endpoint'] ?? null;
            $sunset = $entry['sunset'] ?? null;
            if (! $endpoint || ! $sunset) {
                continue;
            }
            if (Carbon::parse($sunset)->startOfDay()->gt($now->copy()->startOfDay())) {
                continue; // still inside the grace window
            }

            $out[] = [
                'endpoint' => $endpoint,
                'sunset' => $sunset,
                // apiv2 already emits the Fiber route-pattern form ("GET /message/:id"),
                // which is exactly what the Loki hit lines are keyed by.
                'logged_endpoint' => $endpoint,
            ];
        }

        return $out;
    }

    /**
     * @return array<int, mixed>|null
     */
    private function fetchRegistry(): ?array
    {
        $url = config('freegle.apiv2_deprecated_url');
        try {
            $resp = Http::timeout(30)->get($url);
        } catch (\Throwable $e) {
            Log::warning('DeprecatedEndpointService: registry fetch failed: '.$e->getMessage());

            return null;
        }
        if (! $resp->ok()) {
            Log::warning('DeprecatedEndpointService: registry fetch non-200: '.$resp->status());

            return null;
        }

        $json = $resp->json();

        return is_array($json) ? $json : null;
    }
}
