package rippling

import (
	"encoding/base64"
	"testing"
)

// goldenVectorB64 is the SAME bytes asserted in iznik-batch's
// CellSetServiceTest.php and iznik-server-go/test/firstreply_test.go's
// frCellsGoldenVectorB64 - generated by the real Go encoder
// (iznik-reach-cellset/cellset.FromPolygonWKT) for
// POLYGON((0 0,0.003 0,0.003 0.003,0 0.003,0 0)), an 11x11-cell grid (the
// 10x10 square padded by one because its own boundary sits exactly on a
// lattice line). All three languages/packages test against literally
// identical bytes, not three self-consistent implementations that could
// silently disagree at a boundary.
const goldenVectorB64 = "Q0NTMQAAAAAAAAAACwAAAAsAAAAACgEKAQoBCgEKAQoBCgEKAQoBCgw="

func mustDecodeGolden(t *testing.T) *DecodedCellSet {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(goldenVectorB64)
	if err != nil {
		t.Fatalf("bad test fixture: %v", err)
	}
	cs, err := DecodeCellSet(b)
	if err != nil {
		t.Fatalf("DecodeCellSet: %v", err)
	}
	return cs
}

func TestDecodeCellSet_GoldenVectorInteriorPoint(t *testing.T) {
	cs := mustDecodeGolden(t)
	if !cs.Contains(0.0015, 0.0015) {
		t.Error("centre of the golden vector's square must be contained")
	}
}

func TestDecodeCellSet_GoldenVectorFarOutside(t *testing.T) {
	cs := mustDecodeGolden(t)
	if cs.Contains(5, 5) {
		t.Error("a point far outside the grid must not be contained")
	}
	if cs.Contains(-0.0001, -0.0001) {
		t.Error("a point just before the grid must not be contained")
	}
}

func TestDecodeCellSet_RejectsBadMagic(t *testing.T) {
	if _, err := DecodeCellSet(make([]byte, 20)); err == nil {
		t.Error("all-zero bytes (wrong magic) must be rejected")
	}
}

func TestDecodeCellSet_RejectsTruncatedHeader(t *testing.T) {
	if _, err := DecodeCellSet([]byte{0x43, 0x43, 0x53, 0x31}); err == nil {
		t.Error("a header shorter than the fixed size must be rejected")
	}
}

func TestDecodeCellSet_RejectsZeroSizedGrid(t *testing.T) {
	b := make([]byte, 20)
	b[0], b[1], b[2], b[3] = 0x43, 0x43, 0x53, 0x31 // magic, cols/rows left 0
	if _, err := DecodeCellSet(b); err == nil {
		t.Error("a zero-sized grid must be rejected")
	}
}

func TestDecodeCellSet_OutOfBoundsNeverWraps(t *testing.T) {
	cs := mustDecodeGolden(t)
	if cs.Contains(-100, -100) || cs.Contains(100, 100) {
		t.Error("a large negative/positive coordinate must not wrap into a valid index")
	}
}
