<?php

namespace Tests\Unit\Services\Ripple;

use App\Services\Ripple\CellSetService;
use Tests\TestCase;

/**
 * decode()/contains() must agree byte-for-byte with the Go encoder
 * (iznik-reach-cellset/cellset), which is the ONLY place cellset bytes are
 * produced. GOLDEN_VECTOR was generated by that real Go code (not written
 * by hand) for POLYGON((0 0,0.003 0,0.003 0.003,0 0.003,0 0)) - a 10x10-cell
 * square at the 0.0003-degree lattice, padded to 11x11 because the polygon's
 * own boundary sits exactly on a lattice line (the extra row/column stays
 * entirely clear, a known cosmetic inefficiency, not a correctness issue).
 * Any format drift between the two languages breaks this test, not a
 * self-consistency check that could drift with it.
 */
class CellSetServiceTest extends TestCase
{
    private const GOLDEN_VECTOR = 'Q0NTMQAAAAAAAAAACwAAAAsAAAAACgEKAQoBCgEKAQoBCgEKAQoBCgw=';

    private function service(): CellSetService
    {
        return new CellSetService();
    }

    public function test_decodes_golden_vector_header(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        $this->assertSame(0, $decoded['minCol']);
        $this->assertSame(0, $decoded['minRow']);
        $this->assertSame(11, $decoded['cols']);
        $this->assertSame(11, $decoded['rows']);
    }

    public function test_contains_agrees_with_the_go_encoder_on_an_interior_point(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(0.0015, 0.0015) == true
        $this->assertTrue($this->service()->contains($decoded, 0.0015, 0.0015));
    }

    public function test_contains_agrees_with_the_go_encoder_on_a_far_outside_point(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(5, 5) == false
        $this->assertFalse($this->service()->contains($decoded, 5, 5));
    }

    public function test_contains_agrees_with_the_go_encoder_just_before_the_grid(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(-0.0001, -0.0001) == false
        $this->assertFalse($this->service()->contains($decoded, -0.0001, -0.0001));
    }

    public function test_decode_rejects_bad_magic(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode(str_repeat("\x00", 20));
    }

    public function test_decode_rejects_truncated_header(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode("\x43\x43\x53\x31");
    }

    public function test_decode_rejects_zero_sized_grid(): void
    {
        // magic + minCol=0 + minRow=0 + cols=0 + rows=0
        $bytes = "\x43\x43\x53\x31" . str_repeat("\x00", 16);
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode($bytes);
    }

    public function test_contains_outside_the_grid_bounds_is_false_not_a_wraparound(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // A negative row/col difference must not wrap into a positive index
        // via PHP's own array indexing semantics.
        $this->assertFalse($this->service()->contains($decoded, -100, -100));
        $this->assertFalse($this->service()->contains($decoded, 100, 100));
    }
}
