<?php

namespace Tests\Unit\Services\Ripple;

use App\Services\Ripple\CellSetService;
use Tests\TestCase;

/**
 * decode()/contains() must agree byte-for-byte with the Go encoder
 * (iznik-reach-cellset/cellset), which is the ONLY place cellset bytes are
 * produced. GOLDEN_VECTOR was generated by that real Go code (not written
 * by hand) for POLYGON((0 0,0.003 0,0.003 0.003,0 0.003,0 0)) - a 10x10-cell
 * square at the 0.0003-degree lattice, padded to 11x11 because the polygon's
 * own boundary sits exactly on a lattice line (the extra row/column stays
 * entirely clear, a known cosmetic inefficiency, not a correctness issue).
 * Any format drift between the two languages breaks this test, not a
 * self-consistency check that could drift with it.
 */
class CellSetServiceTest extends TestCase
{
    private const GOLDEN_VECTOR = 'Q0NTMQAAAAAAAAAACwAAAAsAAAAACgEKAQoBCgEKAQoBCgEKAQoBCgw=';

    /**
     * A grid whose minCol AND minRow are both NEGATIVE, from the same real
     * rasteriser: POLYGON((-0.0009 -0.0006, 0.0006 -0.0006, 0.0006 0.0006,
     * -0.0009 0.0006, -0.0009 -0.0006)) - a box straddling both lng 0 and
     * lat 0. Header: minCol=-3 minRow=-2 cols=6 rows=5, 20 covered cells.
     *
     * Pinned separately from GOLDEN_VECTOR, which has minCol=minRow=0 and so
     * never exercised the sign path at all. It matters because the UK sits at
     * NEGATIVE longitude and Greenwich is lng 0, so real reaches straddle the
     * meridian routinely - and the header carries these as int32 written
     * through uint32, which is where a sign bug would hide. The identical
     * constant and the identical probes are asserted on the Go side
     * (rippling/postdrop_test.go), so the two languages are locked together
     * on this case rather than merely believed to agree.
     */
    private const GOLDEN_NEGATIVE_OFFSETS = 'Q0NTMf3////+////BgAAAAUAAAAABQEFAQUBBQc=';

    public function test_negative_grid_offsets_decode_probe_and_re_encode(): void
    {
        $svc = new CellSetService();
        $bytes = base64_decode(self::GOLDEN_NEGATIVE_OFFSETS);

        $decoded = $svc->decode($bytes);
        $this->assertSame(-3, $decoded['minCol'], 'a negative minCol must survive the uint32 round trip');
        $this->assertSame(-2, $decoded['minRow'], 'a negative minRow must survive the uint32 round trip');
        $this->assertCount(20, $decoded['set']);

        // The same four probes the Go side asserts on the same bytes.
        $cases = [
            [-0.00075, -0.00045, true],   // inside, both coordinates negative
            [0.00045, 0.00045, true],     // inside, both positive
            [-0.00105, 0.0, false],       // west of minCol
            [0.00075, 0.0, false],        // east of minCol + cols
        ];
        foreach ($cases as [$lng, $lat, $want]) {
            $stream = $svc->containsEncoded($bytes, $lng, $lat);
            $this->assertSame($want, $stream, sprintf('streaming probe at %.5f,%.5f', $lng, $lat));
            $this->assertSame(
                $stream,
                $svc->contains($decoded, $lng, $lat),
                sprintf('the streaming probe and a full decode disagree at %.5f,%.5f', $lng, $lat)
            );
        }

        // Re-encoding must reproduce the bytes exactly, negative header and
        // all - this is what lets the clip write a shrunk grid back.
        $this->assertSame(
            self::GOLDEN_NEGATIVE_OFFSETS,
            base64_encode($svc->encode($decoded)),
            're-encode must be byte-identical for a negative-offset grid'
        );
    }

    private function service(): CellSetService
    {
        return new CellSetService();
    }

    public function test_decodes_golden_vector_header(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        $this->assertSame(0, $decoded['minCol']);
        $this->assertSame(0, $decoded['minRow']);
        $this->assertSame(11, $decoded['cols']);
        $this->assertSame(11, $decoded['rows']);
    }

    public function test_contains_agrees_with_the_go_encoder_on_an_interior_point(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(0.0015, 0.0015) == true
        $this->assertTrue($this->service()->contains($decoded, 0.0015, 0.0015));
    }

    public function test_contains_agrees_with_the_go_encoder_on_a_far_outside_point(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(5, 5) == false
        $this->assertFalse($this->service()->contains($decoded, 5, 5));
    }

    public function test_contains_agrees_with_the_go_encoder_just_before_the_grid(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Go: cs.Contains(-0.0001, -0.0001) == false
        $this->assertFalse($this->service()->contains($decoded, -0.0001, -0.0001));
    }

    public function test_decode_rejects_bad_magic(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode(str_repeat("\x00", 20));
    }

    public function test_decode_rejects_truncated_header(): void
    {
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode("\x43\x43\x53\x31");
    }

    public function test_decode_rejects_zero_sized_grid(): void
    {
        // magic + minCol=0 + minRow=0 + cols=0 + rows=0
        $bytes = "\x43\x43\x53\x31" . str_repeat("\x00", 16);
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode($bytes);
    }

    public function test_decode_rejects_an_absurdly_large_grid_instead_of_exhausting_the_process(): void
    {
        // Cols and Rows are each unsigned 32-bit, so a corrupt header can claim
        // 1.8e19 cells. Refusing it means "fall back to the polygon", which
        // every caller already handles; running out of memory does not.
        $bytes = "\x43\x43\x53\x31"
            . pack('VVVV', 0, 0, 0xFFFFFFFF, 0xFFFFFFFF);
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->decode($bytes);
    }

    public function test_rasterize_refuses_a_200_that_is_not_a_cell_set(): void
    {
        // An empty or truncated 200 - a misrouted request, a proxy's own
        // response, a server too old to know the endpoint - must not be stored.
        // Storing it leaves a column that looks converted while every reader
        // fails to decode it and falls back for the life of the row.
        \Illuminate\Support\Facades\Http::fake([
            '*/v1/reach/rasterize' => \Illuminate\Support\Facades\Http::response('', 200),
        ]);
        $this->assertNull($this->service()->rasterize('POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))'));

        \Illuminate\Support\Facades\Http::fake([
            '*/v1/reach/rasterize' => \Illuminate\Support\Facades\Http::response('<html>oops</html>', 200),
        ]);
        $this->assertNull($this->service()->rasterize('POLYGON((0 0, 1 0, 1 1, 0 1, 0 0))'));
    }

    public function test_contains_outside_the_grid_bounds_is_false_not_a_wraparound(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // A negative row/col difference must not wrap into a positive index
        // via PHP's own array indexing semantics.
        $this->assertFalse($this->service()->contains($decoded, -100, -100));
        $this->assertFalse($this->service()->contains($decoded, 100, 100));
    }

    // ── containsEncoded: the read path, which must never decode ──
    //
    // decode() materialises one array entry per COVERED cell, so it costs in
    // proportion to area rather than to the compressed size: a
    // production-sized reach (4,334 x 1,634 cells) measured 317ms and 128MB.
    // That is more than the SQL the cell set exists to replace, and this is
    // the reply gate. containsEncoded walks the run stream for the one cell
    // asked about and allocates nothing (measured 0.002ms, 0 MB).

    public function test_contains_encoded_agrees_with_decode_everywhere(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Every cell of the golden vector's 11x11 grid, plus a margin outside
        // it: the two paths must give the same answer at every one.
        for ($row = -2; $row < 13; $row++) {
            for ($col = -2; $col < 13; $col++) {
                $lng = ($col + 0.5) * 0.0003;
                $lat = ($row + 0.5) * 0.0003;
                $this->assertSame(
                    $this->service()->contains($decoded, $lng, $lat),
                    $this->service()->containsEncoded($bytes, $lng, $lat),
                    "the two paths disagree at cell ($col, $row)"
                );
            }
        }
    }

    public function test_contains_encoded_agrees_with_the_go_encoder(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);

        // The same three points the decode-based tests above assert, so the
        // read path is pinned to the real encoder's output, not to our decoder.
        $this->assertTrue($this->service()->containsEncoded($bytes, 0.0015, 0.0015));
        $this->assertFalse($this->service()->containsEncoded($bytes, 5, 5));
        $this->assertFalse($this->service()->containsEncoded($bytes, -0.0001, -0.0001));
    }

    public function test_contains_encoded_says_it_cannot_answer_rather_than_guessing(): void
    {
        // Null, not false: a caller must be able to tell "outside the reach"
        // from "these bytes are unusable" so it can fall back to the polygon.
        // Answering false would silently refuse every reply on a bad blob.
        $this->assertNull($this->service()->containsEncoded('', 0.0015, 0.0015));
        $this->assertNull($this->service()->containsEncoded('not a cell set at all', 0.0015, 0.0015));
        $this->assertNull($this->service()->containsEncoded(str_repeat("\x00", 20), 0.0015, 0.0015));

        // Header intact, run stream cut short: the point is inside the grid's
        // bounds but the stream never reaches it.
        $truncated = substr(base64_decode(self::GOLDEN_VECTOR), 0, self::HEADER_BYTES + 2);
        $this->assertNull($this->service()->containsEncoded($truncated, 0.0015, 0.0015));
    }

    public function test_contains_encoded_is_false_not_null_outside_the_grid(): void
    {
        // Outside the stored bounds is a real answer, and must not be confused
        // with "cannot say" - a point far from the reach is definitely not in
        // it, and should not send the caller to the polygon.
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $this->assertFalse($this->service()->containsEncoded($bytes, -100, -100));
        $this->assertFalse($this->service()->containsEncoded($bytes, 100, 100));
    }

    private const HEADER_BYTES = 20;

    public function test_encode_round_trips_the_golden_vector_byte_for_byte(): void
    {
        $bytes = base64_decode(self::GOLDEN_VECTOR);
        $decoded = $this->service()->decode($bytes);

        // Proves encode() is byte-identical to the real Go encoder's output
        // for this vector, not merely self-consistent with our own decode().
        $this->assertSame($bytes, $this->service()->encode($decoded));
    }

    /**
     * A full 3x3 grid at (minCol=0,minRow=0) and a full 3x3 grid at
     * (minCol=1,minRow=1) overlap in the bottom-right 2x2 of the first -
     * global cells (1,1),(2,1),(1,2),(2,2). Hand-built (not from a
     * rasteriser, which PHP does not have) to exercise subtract()'s global-
     * coordinate translation directly, mirroring
     * iznik-spatial-go/cellset/subtract_test.go's cases.
     */
    private function fullGrid(int $minCol, int $minRow, int $cols, int $rows): array
    {
        $set = [];
        for ($i = 0; $i < $cols * $rows; $i++) {
            $set[$i] = true;
        }

        return ['minCol' => $minCol, 'minRow' => $minRow, 'cols' => $cols, 'rows' => $rows, 'set' => $set];
    }

    public function test_subtract_removes_overlapping_cells_only(): void
    {
        $a = $this->fullGrid(0, 0, 3, 3);
        $b = $this->fullGrid(1, 1, 3, 3);

        $result = $this->service()->subtract($a, $b);

        // Untouched corner (global 0,0 -> local idx 0) survives.
        $this->assertTrue(isset($result['set'][0]));
        // Overlapping corner (global 2,2 -> local idx 8) is cleared.
        $this->assertFalse(isset($result['set'][8]));
        $this->assertCount(5, $result['set']);
    }

    public function test_subtract_no_overlap_leaves_it_unchanged(): void
    {
        $a = $this->fullGrid(0, 0, 3, 3);
        $farAway = $this->fullGrid(100, 100, 1, 1);

        $result = $this->service()->subtract($a, $farAway);

        $this->assertCount(9, $result['set']);
    }

    public function test_subtract_total_overlap_empties_the_result(): void
    {
        $a = $this->fullGrid(0, 0, 3, 3);
        $coversAll = $this->fullGrid(-1, -1, 5, 5);

        $result = $this->service()->subtract($a, $coversAll);

        $this->assertCount(0, $result['set']);
    }

    public function test_subtract_does_not_mutate_either_operand(): void
    {
        $a = $this->fullGrid(0, 0, 3, 3);
        $b = $this->fullGrid(1, 1, 3, 3);

        $this->service()->subtract($a, $b);

        $this->assertCount(9, $a['set']);
        $this->assertCount(9, $b['set']);
    }

    public function test_subtract_result_round_trips_through_encode_and_decode(): void
    {
        $a = $this->fullGrid(0, 0, 3, 3);
        $b = $this->fullGrid(1, 1, 3, 3);

        $result = $this->service()->subtract($a, $b);
        $reDecoded = $this->service()->decode($this->service()->encode($result));

        $this->assertSame($result['set'], $reDecoded['set']);
        $this->assertSame($result['minCol'], $reDecoded['minCol']);
        $this->assertSame($result['minRow'], $reDecoded['minRow']);
    }

    // ---- the streaming measures and the spatial-server clients added for
    // ---- Stage 3, none of which had a test before.

    /**
     * The reach radius the digest score divides by. Streaming over run
     * endpoints, so the answer must still match a hand-computed haversine to
     * the farthest covered cell.
     */
    public function test_max_distance_from_origin_matches_a_hand_computation(): void
    {
        $svc = new CellSetService();
        // A box 0.003 x 0.003 degrees (10 x 10 cells) with its origin at the
        // south-west corner, so the farthest covered cell is the north-east one.
        $wkt = 'POLYGON((0 51.5, 0.003 51.5, 0.003 51.503, 0 51.503, 0 51.5))';
        $bytes = $svc->rasterize($wkt);
        $this->assertNotNull($bytes, 'the rasteriser must be reachable for this test to mean anything');

        $metres = $svc->maxDistanceMetresFrom($bytes, 0.0, 51.5);
        $this->assertNotNull($metres);

        // North-east cell CENTRE is at roughly (0.00285, 51.50285). Haversine
        // from the origin is ~360m; allow a cell of slack either way.
        $this->assertGreaterThan(300, $metres);
        $this->assertLessThan(420, $metres);
    }

    /**
     * How far outside the reach a held replier is. Zero inside, and a sane
     * positive figure outside - this feeds a miles number a member reads.
     */
    public function test_distance_to_nearest_cell(): void
    {
        $svc = new CellSetService();
        $wkt = 'POLYGON((0 51.5, 0.003 51.5, 0.003 51.503, 0 51.503, 0 51.5))';
        $bytes = $svc->rasterize($wkt);
        $this->assertNotNull($bytes);

        // Inside is exactly zero, not "a few metres to the nearest centre".
        $this->assertSame(0.0, $svc->distanceToNearestCellMetres($bytes, 0.0015, 51.5015));

        // A point ~0.01 degrees east is roughly 700m from the eastern edge at
        // this latitude.
        $out = $svc->distanceToNearestCellMetres($bytes, 0.013, 51.5015);
        $this->assertNotNull($out);
        $this->assertGreaterThan(500, $out);
        $this->assertLessThan(900, $out);

        // Unreadable bytes must answer "cannot say", never a distance.
        $this->assertNull($svc->distanceToNearestCellMetres('rubbish', 0.0, 51.5));
    }

    /** The grid's bounding box as WKT - the cell form of ST_Envelope. */
    public function test_bounds_wkt_covers_the_grid_and_refuses_rubbish(): void
    {
        $svc = new CellSetService();
        $bytes = base64_decode(self::GOLDEN_NEGATIVE_OFFSETS);

        $wkt = $svc->boundsWkt($bytes);
        $this->assertNotNull($wkt);
        $this->assertStringStartsWith('POLYGON((', $wkt);

        // minCol=-3 minRow=-2 cols=6 rows=5 on a 0.0003 lattice, so the box
        // runs from (-0.0009,-0.0006) to (0.0009,0.0009).
        $decoded = $svc->decode($bytes);
        $this->assertSame(-3, $decoded['minCol']);

        // Every covered cell's CENTRE must be strictly inside, which is what
        // the callers rely on. The box CORNERS sit exactly on the boundary,
        // and ST_Contains excludes a boundary point - the same closed-versus-
        // open distinction that accounts for the boundary-band differences in
        // ripple:verify-cells-parity - so they are checked with MBRContains,
        // which includes it.
        foreach ([[-0.00075, -0.00045], [0.00075, 0.00075]] as [$lng, $lat]) {
            $row = \Illuminate\Support\Facades\DB::selectOne(
                'SELECT ST_Contains(ST_GeomFromText(?, 3857), ST_SRID(POINT(?, ?), 3857)) AS c',
                [$wkt, $lng, $lat]
            );
            $this->assertSame(1, (int) $row->c, sprintf('a covered cell centre %f,%f must be inside the bbox', $lng, $lat));
        }
        // The corners are checked arithmetically rather than with a spatial
        // predicate: they sit exactly ON the boundary, and every MySQL
        // "contains" test excludes a boundary point, so a GIS assertion here
        // would be testing that convention rather than the bbox.
        preg_match_all('/-?\d+(?:\.\d+)?/', $wkt, $m);
        $coords = array_map('floatval', $m[0]);
        $lngs = array_values(array_filter($coords, fn ($v, $i) => $i % 2 === 0, ARRAY_FILTER_USE_BOTH));
        $lats = array_values(array_filter($coords, fn ($v, $i) => $i % 2 === 1, ARRAY_FILTER_USE_BOTH));
        $this->assertEqualsWithDelta(-0.0009, min($lngs), 1e-9, 'west edge');
        $this->assertEqualsWithDelta(0.0009, max($lngs), 1e-9, 'east edge');
        $this->assertEqualsWithDelta(-0.0006, min($lats), 1e-9, 'south edge');
        $this->assertEqualsWithDelta(0.0009, max($lats), 1e-9, 'north edge');

        $this->assertNull($svc->boundsWkt('too short'));
    }

    /**
     * The spatial-server clients must return null rather than throw when the
     * server cannot answer - every caller treats null as "fall back" or "admit
     * nobody", and an exception would instead abort a tick or a digest run.
     */
    public function test_spatial_clients_return_null_when_the_server_cannot_answer(): void
    {
        config(['freegle.spatial_server_url' => 'http://127.0.0.1:9']); // nothing listens on discard
        $svc = new CellSetService();

        $this->assertNull($svc->vectorize('irrelevant', 0));
        $this->assertNull($svc->groupsIntersecting('irrelevant'));
        $this->assertNull($svc->reachContaining(51.5, -0.1));
        $this->assertNull($svc->rasterize('POLYGON((0 0,1 0,1 1,0 1,0 0))'));
    }

    /**
     * The tracer round trip, through the real endpoints: a grid traced to a
     * boundary and rasterised again must cover the same cells. This is the
     * property the sandwich-bounds derivation and the map overlay both rest
     * on.
     */
    public function test_vectorize_round_trips_back_to_the_same_coverage(): void
    {
        $svc = new CellSetService();
        $wkt = 'POLYGON((0 51.5, 0.003 51.5, 0.003 51.503, 0 51.503, 0 51.5))';
        $bytes = $svc->rasterize($wkt);
        $this->assertNotNull($bytes);

        $vec = $svc->vectorize($bytes, 0);
        $this->assertNotNull($vec, 'the vectorize endpoint must be reachable');
        $this->assertArrayHasKey('wkt', $vec);

        $back = $svc->rasterize($vec['wkt']);
        $this->assertNotNull($back);

        $a = $svc->decode($bytes);
        $b = $svc->decode($back);
        $this->assertSame(
            count($svc->subtract($a, $b)['set']) + count($svc->subtract($b, $a)['set']),
            0,
            'tracing and re-rasterising must not move a single covered cell'
        );
    }
}
