package electricals

import (
	"encoding/json"

	"github.com/freegle/iznik-server-go/database"
	"github.com/gofiber/fiber/v2"
)

// Public statistics for the /electricals page.
//
// The payload is generated by the Laravel command electricals:stats and stored in
// electricals_stats. It is not computed here: every figure is a rolling twelve-month
// aggregate over messages joined to messages_eee, messages_items and messages_outcomes,
// which is far too heavy to run per request. This handler serves the newest generation.
//
// The payload's shape is owned by ElectricalsStatsService, so it is passed through as
// raw JSON rather than modelled here. Mirroring the struct in two languages would mean
// every added figure needed a Go change too, and the endpoint has no reason to inspect
// the contents.

// statsRow is the newest generated payload.
type statsRow struct {
	GeneratedAt string `gorm:"column:generated_at"`
	Payload     string `gorm:"column:payload"`
}

// Stats returns the most recent electricals statistics payload.
//
// Returns 404 rather than an empty object when nothing has been generated yet, so a page
// that has never had a run is distinguishable from one whose figures are genuinely zero.
func Stats(c *fiber.Ctx) error {
	db := database.DBConn

	var row statsRow

	// Newest generation. electricals_stats keeps a short history so a bad run can be
	// compared against its predecessor; only the latest is ever served.
	result := db.Table("electricals_stats").
		Select("generated_at, payload").
		Order("id DESC").
		Limit(1).
		Scan(&row)

	if result.Error != nil {
		return fiber.NewError(fiber.StatusInternalServerError, "Failed to read electricals stats")
	}

	if row.Payload == "" {
		return fiber.NewError(fiber.StatusNotFound, "No electricals stats have been generated yet")
	}

	// The stored payload is already JSON. Send it as the body rather than decoding and
	// re-encoding, which would reorder keys and cost nothing useful.
	var check json.RawMessage
	if err := json.Unmarshal([]byte(row.Payload), &check); err != nil {
		return fiber.NewError(fiber.StatusInternalServerError, "Stored electricals stats are not valid JSON")
	}

	c.Set("Content-Type", "application/json")
	return c.SendString(row.Payload)
}
