#!/usr/bin/env ruby
# frozen_string_literal: true

# Adds the "Share into Freegle" Share Extension target to ios/App/App.xcodeproj so
# it builds + signs on CircleCI like any other target — no manual Xcode step.
#
# GATED: does nothing unless ENABLE_SHARE_EXTENSION=true. By default it is a no-op,
# so the main app's entitlements + signing are byte-for-byte unaffected and the
# production build is unchanged. Enable ONLY AFTER:
#   1. Registering the App Group `group.org.ilovefreegle.iphone` in the Apple
#      Developer portal and enabling it on BOTH App IDs
#      (org.ilovefreegle.iphone and org.ilovefreegle.iphone.ShareExtension).
#   2. Regenerating the app + extension App Store provisioning profiles so they
#      include that App Group — otherwise signing/export fails.
#
# Idempotent: safe to run on every CI build. Unlike the NSE, the source is
# committed (ios/App/ShareExtension/), so there is nothing to copy in.
#
# Requires the `xcodeproj` gem (a fastlane dependency; run under `bundle exec`).

require 'fileutils'
require 'xcodeproj'

unless ENV['ENABLE_SHARE_EXTENSION'] == 'true'
  puts 'add_share_extension_target: ENABLE_SHARE_EXTENSION not set — skipping (no-op).'
  exit 0
end

EXT_NAME      = 'ShareExtension'
APP_TARGET    = 'Freegle'
APP_BUNDLE_ID = 'org.ilovefreegle.iphone'
EXT_BUNDLE_ID = "#{APP_BUNDLE_ID}.#{EXT_NAME}"
APP_GROUP     = 'group.org.ilovefreegle.iphone'
DEPLOY_TARGET = '14.0'

root        = File.expand_path('..', __dir__) # fastlane/ -> project root
proj_path   = File.join(root, 'ios/App/App.xcodeproj')
ext_dir     = File.join(root, 'ios/App', EXT_NAME)
app_entitle = File.join(root, 'ios/App/App/App.entitlements')

unless File.directory?(File.dirname(proj_path))
  warn "add_share_extension_target: #{proj_path} not found — has cap sync run? Skipping."
  exit 0
end
unless File.exist?(File.join(ext_dir, 'ShareViewController.swift'))
  warn "add_share_extension_target: source not found in #{ext_dir} — skipping."
  exit 0
end

project    = Xcodeproj::Project.open(proj_path)
app_target = project.targets.find { |t| t.name == APP_TARGET }
unless app_target
  warn "add_share_extension_target: main target '#{APP_TARGET}' not found — skipping."
  exit 0
end

def apply_ext_settings(config)
  s = config.build_settings
  s['PRODUCT_BUNDLE_IDENTIFIER']  = EXT_BUNDLE_ID
  s['PRODUCT_NAME']               = '$(TARGET_NAME)'
  s['INFOPLIST_FILE']             = "#{EXT_NAME}/Info.plist"
  s['CODE_SIGN_ENTITLEMENTS']     = "#{EXT_NAME}/ShareExtension.entitlements"
  s['SWIFT_VERSION']              = '5.0'
  s['IPHONEOS_DEPLOYMENT_TARGET'] = DEPLOY_TARGET
  s['TARGETED_DEVICE_FAMILY']     = '1,2'
  s['CODE_SIGN_STYLE']            = 'Manual'
  s['SKIP_INSTALL']               = 'NO'
  s['MARKETING_VERSION']        ||= '1.0'
  s['CURRENT_PROJECT_VERSION']  ||= '1'
end

ext_target = project.targets.find { |t| t.name == EXT_NAME }
if ext_target
  puts 'add_share_extension_target: target already exists — refreshing settings + file refs'
  ext_target.build_configurations.each { |c| apply_ext_settings(c) }
else
  puts "add_share_extension_target: creating '#{EXT_NAME}' app-extension target"
  ext_target = project.new_target(:app_extension, EXT_NAME, :ios, DEPLOY_TARGET)
  ext_target.build_configurations.each { |c| apply_ext_settings(c) }

  # Build the app target after the extension, and embed the .appex in the app.
  app_target.add_dependency(ext_target)

  embed = app_target.copy_files_build_phases.find { |p| p.symbol_dst_subfolder_spec == :plug_ins }
  if embed.nil?
    embed = app_target.new_copy_files_build_phase('Embed App Extensions')
    embed.symbol_dst_subfolder_spec = :plug_ins
  end
  build_file = embed.add_file_reference(ext_target.product_reference)
  build_file.settings = { 'ATTRIBUTES' => ['RemoveHeadersOnCopy'] }
end

# Group + file references, relative to SOURCE_ROOT (the .xcodeproj dir = ios/App).
group = project.main_group.find_subpath(EXT_NAME, true)
group.set_source_tree('SOURCE_ROOT')
group.set_path(EXT_NAME)

swift_name = 'ShareViewController.swift'
swift_ref  = group.files.find { |f| f.display_name == swift_name } ||
             group.new_reference(swift_name)
unless ext_target.source_build_phase.files_references.include?(swift_ref)
  ext_target.add_file_references([swift_ref])
end
['Info.plist', 'ShareExtension.entitlements'].each do |fname|
  group.new_reference(fname) unless group.files.any? { |f| f.display_name == fname }
end

# The main app must join the same App Group so it can read what the extension
# wrote. Patch App.entitlements at BUILD TIME only (never committed), so the
# default build is untouched. The app's provisioning profile must already
# include this App Group (regenerated by hand — see header).
if File.exist?(app_entitle)
  xml = File.read(app_entitle)
  unless xml.include?(APP_GROUP)
    inject = <<-PLIST
	<key>com.apple.security.application-groups</key>
	<array>
		<string>#{APP_GROUP}</string>
	</array>
PLIST
    xml = xml.sub('</dict>', "#{inject}</dict>")
    File.write(app_entitle, xml)
    puts "add_share_extension_target: added #{APP_GROUP} to main app entitlements (build-time)"
  end
end

project.save
puts "add_share_extension_target: done (#{EXT_BUNDLE_ID})"
