<?php
/**
 * GetPostAndRelatedData200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trash Nothing
 *
 * This is the REST API for [trashnothing.com](https://trashnothing.com).  To learn more about the API or to register your app for use with the API visit the [Trash Nothing Developer page](https://trashnothing.com/app/developer).  NOTE: All date-time values are [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) and are in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) (eg. 2019-02-03T01:23:53).
 *
 * The version of the OpenAPI document: 1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetPostAndRelatedData200Response Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetPostAndRelatedData200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'get_post_and_related_data_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'post' => '\OpenAPI\Client\Model\Post',
        'author' => '\OpenAPI\Client\Model\User',
        'author_posts' => '\OpenAPI\Client\Model\Post[]',
        'author_offer_count' => 'int',
        'author_wanted_count' => 'int',
        'groups' => '\OpenAPI\Client\Model\Group[]',
        'user_can_reply' => 'bool',
        'viewed' => 'bool',
        'replied' => 'bool',
        'bookmarked' => 'bool',
        'hidden' => 'bool'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'post' => null,
        'author' => null,
        'author_posts' => null,
        'author_offer_count' => null,
        'author_wanted_count' => null,
        'groups' => null,
        'user_can_reply' => null,
        'viewed' => null,
        'replied' => null,
        'bookmarked' => null,
        'hidden' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'post' => false,
        'author' => false,
        'author_posts' => false,
        'author_offer_count' => false,
        'author_wanted_count' => false,
        'groups' => false,
        'user_can_reply' => false,
        'viewed' => false,
        'replied' => false,
        'bookmarked' => false,
        'hidden' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'post' => 'post',
        'author' => 'author',
        'author_posts' => 'author_posts',
        'author_offer_count' => 'author_offer_count',
        'author_wanted_count' => 'author_wanted_count',
        'groups' => 'groups',
        'user_can_reply' => 'user_can_reply',
        'viewed' => 'viewed',
        'replied' => 'replied',
        'bookmarked' => 'bookmarked',
        'hidden' => 'hidden'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'post' => 'setPost',
        'author' => 'setAuthor',
        'author_posts' => 'setAuthorPosts',
        'author_offer_count' => 'setAuthorOfferCount',
        'author_wanted_count' => 'setAuthorWantedCount',
        'groups' => 'setGroups',
        'user_can_reply' => 'setUserCanReply',
        'viewed' => 'setViewed',
        'replied' => 'setReplied',
        'bookmarked' => 'setBookmarked',
        'hidden' => 'setHidden'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'post' => 'getPost',
        'author' => 'getAuthor',
        'author_posts' => 'getAuthorPosts',
        'author_offer_count' => 'getAuthorOfferCount',
        'author_wanted_count' => 'getAuthorWantedCount',
        'groups' => 'getGroups',
        'user_can_reply' => 'getUserCanReply',
        'viewed' => 'getViewed',
        'replied' => 'getReplied',
        'bookmarked' => 'getBookmarked',
        'hidden' => 'getHidden'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('post', $data ?? [], null);
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('author_posts', $data ?? [], null);
        $this->setIfExists('author_offer_count', $data ?? [], null);
        $this->setIfExists('author_wanted_count', $data ?? [], null);
        $this->setIfExists('groups', $data ?? [], null);
        $this->setIfExists('user_can_reply', $data ?? [], null);
        $this->setIfExists('viewed', $data ?? [], null);
        $this->setIfExists('replied', $data ?? [], null);
        $this->setIfExists('bookmarked', $data ?? [], null);
        $this->setIfExists('hidden', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets post
     *
     * @return \OpenAPI\Client\Model\Post|null
     */
    public function getPost()
    {
        return $this->container['post'];
    }

    /**
     * Sets post
     *
     * @param \OpenAPI\Client\Model\Post|null $post post
     *
     * @return self
     */
    public function setPost($post)
    {
        if (is_null($post)) {
            throw new \InvalidArgumentException('non-nullable post cannot be null');
        }
        $this->container['post'] = $post;

        return $this;
    }

    /**
     * Gets author
     *
     * @return \OpenAPI\Client\Model\User|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param \OpenAPI\Client\Model\User|null $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            throw new \InvalidArgumentException('non-nullable author cannot be null');
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets author_posts
     *
     * @return \OpenAPI\Client\Model\Post[]|null
     */
    public function getAuthorPosts()
    {
        return $this->container['author_posts'];
    }

    /**
     * Sets author_posts
     *
     * @param \OpenAPI\Client\Model\Post[]|null $author_posts Other active posts from the post author in the last 90 days. A maximum of 30 posts will be returned.
     *
     * @return self
     */
    public function setAuthorPosts($author_posts)
    {
        if (is_null($author_posts)) {
            throw new \InvalidArgumentException('non-nullable author_posts cannot be null');
        }
        $this->container['author_posts'] = $author_posts;

        return $this;
    }

    /**
     * Gets author_offer_count
     *
     * @return int|null
     */
    public function getAuthorOfferCount()
    {
        return $this->container['author_offer_count'];
    }

    /**
     * Sets author_offer_count
     *
     * @param int|null $author_offer_count Count of offer posts made by the post author in the last 90 days.
     *
     * @return self
     */
    public function setAuthorOfferCount($author_offer_count)
    {
        if (is_null($author_offer_count)) {
            throw new \InvalidArgumentException('non-nullable author_offer_count cannot be null');
        }
        $this->container['author_offer_count'] = $author_offer_count;

        return $this;
    }

    /**
     * Gets author_wanted_count
     *
     * @return int|null
     */
    public function getAuthorWantedCount()
    {
        return $this->container['author_wanted_count'];
    }

    /**
     * Sets author_wanted_count
     *
     * @param int|null $author_wanted_count Count of wanted posts made by the post author in the last 90 days.
     *
     * @return self
     */
    public function setAuthorWantedCount($author_wanted_count)
    {
        if (is_null($author_wanted_count)) {
            throw new \InvalidArgumentException('non-nullable author_wanted_count cannot be null');
        }
        $this->container['author_wanted_count'] = $author_wanted_count;

        return $this;
    }

    /**
     * Gets groups
     *
     * @return \OpenAPI\Client\Model\Group[]|null
     */
    public function getGroups()
    {
        return $this->container['groups'];
    }

    /**
     * Sets groups
     *
     * @param \OpenAPI\Client\Model\Group[]|null $groups The groups the post is published on.
     *
     * @return self
     */
    public function setGroups($groups)
    {
        if (is_null($groups)) {
            throw new \InvalidArgumentException('non-nullable groups cannot be null');
        }
        $this->container['groups'] = $groups;

        return $this;
    }

    /**
     * Gets user_can_reply
     *
     * @return bool|null
     */
    public function getUserCanReply()
    {
        return $this->container['user_can_reply'];
    }

    /**
     * Sets user_can_reply
     *
     * @param bool|null $user_can_reply Whether or not the current user (if any) can reply to this post. Unverified users cannot reply to posts until they verify their account.
     *
     * @return self
     */
    public function setUserCanReply($user_can_reply)
    {
        if (is_null($user_can_reply)) {
            throw new \InvalidArgumentException('non-nullable user_can_reply cannot be null');
        }
        $this->container['user_can_reply'] = $user_can_reply;

        return $this;
    }

    /**
     * Gets viewed
     *
     * @return bool|null
     */
    public function getViewed()
    {
        return $this->container['viewed'];
    }

    /**
     * Sets viewed
     *
     * @param bool|null $viewed Whether or not the current user has previously viewed this post.  Will be null for api key requests and for the current users' posts.
     *
     * @return self
     */
    public function setViewed($viewed)
    {
        if (is_null($viewed)) {
            throw new \InvalidArgumentException('non-nullable viewed cannot be null');
        }
        $this->container['viewed'] = $viewed;

        return $this;
    }

    /**
     * Gets replied
     *
     * @return bool|null
     */
    public function getReplied()
    {
        return $this->container['replied'];
    }

    /**
     * Sets replied
     *
     * @param bool|null $replied Whether or not the current user has replied to this post.  Will be null for api key requests and for the current users' posts.
     *
     * @return self
     */
    public function setReplied($replied)
    {
        if (is_null($replied)) {
            throw new \InvalidArgumentException('non-nullable replied cannot be null');
        }
        $this->container['replied'] = $replied;

        return $this;
    }

    /**
     * Gets bookmarked
     *
     * @return bool|null
     */
    public function getBookmarked()
    {
        return $this->container['bookmarked'];
    }

    /**
     * Sets bookmarked
     *
     * @param bool|null $bookmarked Whether or not the current user has bookmarked this post.  Will be null for api key requests and for the current users' posts.
     *
     * @return self
     */
    public function setBookmarked($bookmarked)
    {
        if (is_null($bookmarked)) {
            throw new \InvalidArgumentException('non-nullable bookmarked cannot be null');
        }
        $this->container['bookmarked'] = $bookmarked;

        return $this;
    }

    /**
     * Gets hidden
     *
     * @return bool|null
     */
    public function getHidden()
    {
        return $this->container['hidden'];
    }

    /**
     * Sets hidden
     *
     * @param bool|null $hidden Whether the current user has hidden the post author.
     *
     * @return self
     */
    public function setHidden($hidden)
    {
        if (is_null($hidden)) {
            throw new \InvalidArgumentException('non-nullable hidden cannot be null');
        }
        $this->container['hidden'] = $hidden;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


