<?php
/**
 * Group
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trash Nothing
 *
 * This is the REST API for [trashnothing.com](https://trashnothing.com).  To learn more about the API or to register your app for use with the API visit the [Trash Nothing Developer page](https://trashnothing.com/app/developer).  NOTE: All date-time values are [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) and are in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) (eg. 2019-02-03T01:23:53).
 *
 * The version of the OpenAPI document: 1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Group Class Doc Comment
 *
 * @category Class
 * @description Groups are run by volunteer moderators and provide a way to group activity in a specific location. Because each group is usually run by different people, there can be variations in rules from group to group (eg. who is allowed to join, what is allowed to be posted, how often reposts are allowed).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Group implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Group';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'group_id' => 'string',
        'name' => 'string',
        'identifier' => 'string',
        'homepage' => 'string',
        'member_count' => 'int',
        'latitude' => 'float',
        'longitude' => 'float',
        'timezone' => 'string',
        'open_membership' => 'bool',
        'open_archives' => 'bool',
        'has_questions' => 'bool',
        'country' => '\OpenAPI\Client\Model\GroupCountry',
        'region' => '\OpenAPI\Client\Model\GroupRegion',
        'membership' => '\OpenAPI\Client\Model\GroupMembership'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'group_id' => null,
        'name' => null,
        'identifier' => null,
        'homepage' => null,
        'member_count' => null,
        'latitude' => null,
        'longitude' => null,
        'timezone' => null,
        'open_membership' => null,
        'open_archives' => null,
        'has_questions' => null,
        'country' => null,
        'region' => null,
        'membership' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'group_id' => false,
        'name' => false,
        'identifier' => false,
        'homepage' => false,
        'member_count' => false,
        'latitude' => false,
        'longitude' => false,
        'timezone' => false,
        'open_membership' => false,
        'open_archives' => false,
        'has_questions' => false,
        'country' => false,
        'region' => false,
        'membership' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'group_id' => 'group_id',
        'name' => 'name',
        'identifier' => 'identifier',
        'homepage' => 'homepage',
        'member_count' => 'member_count',
        'latitude' => 'latitude',
        'longitude' => 'longitude',
        'timezone' => 'timezone',
        'open_membership' => 'open_membership',
        'open_archives' => 'open_archives',
        'has_questions' => 'has_questions',
        'country' => 'country',
        'region' => 'region',
        'membership' => 'membership'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'group_id' => 'setGroupId',
        'name' => 'setName',
        'identifier' => 'setIdentifier',
        'homepage' => 'setHomepage',
        'member_count' => 'setMemberCount',
        'latitude' => 'setLatitude',
        'longitude' => 'setLongitude',
        'timezone' => 'setTimezone',
        'open_membership' => 'setOpenMembership',
        'open_archives' => 'setOpenArchives',
        'has_questions' => 'setHasQuestions',
        'country' => 'setCountry',
        'region' => 'setRegion',
        'membership' => 'setMembership'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'group_id' => 'getGroupId',
        'name' => 'getName',
        'identifier' => 'getIdentifier',
        'homepage' => 'getHomepage',
        'member_count' => 'getMemberCount',
        'latitude' => 'getLatitude',
        'longitude' => 'getLongitude',
        'timezone' => 'getTimezone',
        'open_membership' => 'getOpenMembership',
        'open_archives' => 'getOpenArchives',
        'has_questions' => 'getHasQuestions',
        'country' => 'getCountry',
        'region' => 'getRegion',
        'membership' => 'getMembership'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('group_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('homepage', $data ?? [], null);
        $this->setIfExists('member_count', $data ?? [], null);
        $this->setIfExists('latitude', $data ?? [], null);
        $this->setIfExists('longitude', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('open_membership', $data ?? [], null);
        $this->setIfExists('open_archives', $data ?? [], null);
        $this->setIfExists('has_questions', $data ?? [], null);
        $this->setIfExists('country', $data ?? [], null);
        $this->setIfExists('region', $data ?? [], null);
        $this->setIfExists('membership', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets group_id
     *
     * @return string|null
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param string|null $group_id group_id
     *
     * @return self
     */
    public function setGroupId($group_id)
    {
        if (is_null($group_id)) {
            throw new \InvalidArgumentException('non-nullable group_id cannot be null');
        }
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the group (not guaranteed to be unique).
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return string|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param string|null $identifier A unique identifier for the group that is used in URLs.
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            throw new \InvalidArgumentException('non-nullable identifier cannot be null');
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets homepage
     *
     * @return string|null
     */
    public function getHomepage()
    {
        return $this->container['homepage'];
    }

    /**
     * Sets homepage
     *
     * @param string|null $homepage A URL to the group homepage.
     *
     * @return self
     */
    public function setHomepage($homepage)
    {
        if (is_null($homepage)) {
            throw new \InvalidArgumentException('non-nullable homepage cannot be null');
        }
        $this->container['homepage'] = $homepage;

        return $this;
    }

    /**
     * Gets member_count
     *
     * @return int|null
     */
    public function getMemberCount()
    {
        return $this->container['member_count'];
    }

    /**
     * Sets member_count
     *
     * @param int|null $member_count The number of members who belong to the group.
     *
     * @return self
     */
    public function setMemberCount($member_count)
    {
        if (is_null($member_count)) {
            throw new \InvalidArgumentException('non-nullable member_count cannot be null');
        }
        $this->container['member_count'] = $member_count;

        return $this;
    }

    /**
     * Gets latitude
     *
     * @return float|null
     */
    public function getLatitude()
    {
        return $this->container['latitude'];
    }

    /**
     * Sets latitude
     *
     * @param float|null $latitude latitude
     *
     * @return self
     */
    public function setLatitude($latitude)
    {
        if (is_null($latitude)) {
            throw new \InvalidArgumentException('non-nullable latitude cannot be null');
        }
        $this->container['latitude'] = $latitude;

        return $this;
    }

    /**
     * Gets longitude
     *
     * @return float|null
     */
    public function getLongitude()
    {
        return $this->container['longitude'];
    }

    /**
     * Sets longitude
     *
     * @param float|null $longitude longitude
     *
     * @return self
     */
    public function setLongitude($longitude)
    {
        if (is_null($longitude)) {
            throw new \InvalidArgumentException('non-nullable longitude cannot be null');
        }
        $this->container['longitude'] = $longitude;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone The timezone that the group is in (eg. America/New_York).
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            throw new \InvalidArgumentException('non-nullable timezone cannot be null');
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets open_membership
     *
     * @return bool|null
     */
    public function getOpenMembership()
    {
        return $this->container['open_membership'];
    }

    /**
     * Sets open_membership
     *
     * @param bool|null $open_membership When true, the group allows anyone to join.  When false, the group moderators review and approve applicants.
     *
     * @return self
     */
    public function setOpenMembership($open_membership)
    {
        if (is_null($open_membership)) {
            throw new \InvalidArgumentException('non-nullable open_membership cannot be null');
        }
        $this->container['open_membership'] = $open_membership;

        return $this;
    }

    /**
     * Gets open_archives
     *
     * @return bool|null
     */
    public function getOpenArchives()
    {
        return $this->container['open_archives'];
    }

    /**
     * Sets open_archives
     *
     * @param bool|null $open_archives When true, the group posts are viewable by anyone.  When false, the group posts can only be viewed by members of the group.
     *
     * @return self
     */
    public function setOpenArchives($open_archives)
    {
        if (is_null($open_archives)) {
            throw new \InvalidArgumentException('non-nullable open_archives cannot be null');
        }
        $this->container['open_archives'] = $open_archives;

        return $this;
    }

    /**
     * Gets has_questions
     *
     * @return bool|null
     */
    public function getHasQuestions()
    {
        return $this->container['has_questions'];
    }

    /**
     * Sets has_questions
     *
     * @param bool|null $has_questions When true, anyone requesting membership to this group will be required to answer a new membership questionnaire.
     *
     * @return self
     */
    public function setHasQuestions($has_questions)
    {
        if (is_null($has_questions)) {
            throw new \InvalidArgumentException('non-nullable has_questions cannot be null');
        }
        $this->container['has_questions'] = $has_questions;

        return $this;
    }

    /**
     * Gets country
     *
     * @return \OpenAPI\Client\Model\GroupCountry|null
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     *
     * @param \OpenAPI\Client\Model\GroupCountry|null $country country
     *
     * @return self
     */
    public function setCountry($country)
    {
        if (is_null($country)) {
            throw new \InvalidArgumentException('non-nullable country cannot be null');
        }
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets region
     *
     * @return \OpenAPI\Client\Model\GroupRegion|null
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param \OpenAPI\Client\Model\GroupRegion|null $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        if (is_null($region)) {
            throw new \InvalidArgumentException('non-nullable region cannot be null');
        }
        $this->container['region'] = $region;

        return $this;
    }

    /**
     * Gets membership
     *
     * @return \OpenAPI\Client\Model\GroupMembership|null
     */
    public function getMembership()
    {
        return $this->container['membership'];
    }

    /**
     * Sets membership
     *
     * @param \OpenAPI\Client\Model\GroupMembership|null $membership membership
     *
     * @return self
     */
    public function setMembership($membership)
    {
        if (is_null($membership)) {
            throw new \InvalidArgumentException('non-nullable membership cannot be null');
        }
        $this->container['membership'] = $membership;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


