<?php
/**
 * UsersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trash Nothing
 *
 * This is the REST API for [trashnothing.com](https://trashnothing.com).  To learn more about the API or to register your app for use with the API visit the [Trash Nothing Developer page](https://trashnothing.com/app/developer).  NOTE: All date-time values are [UTC](https://en.wikipedia.org/wiki/Coordinated_Universal_Time) and are in [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601) (eg. 2019-02-03T01:23:53).
 *
 * The version of the OpenAPI document: 1.4
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\FormDataProcessor;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * UsersApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UsersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getUserPosts' => [
            'application/json',
        ],
        'searchUserPosts' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getUserPosts
     *
     * List posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: date, active, distance &lt;br /&gt;&lt;br /&gt; Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'date')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPosts'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\GetUserPosts200Response
     */
    public function getUserPosts($user_id, $types, $sources, $sort_by = 'date', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['getUserPosts'][0])
    {
        list($response) = $this->getUserPostsWithHttpInfo($user_id, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);
        return $response;
    }

    /**
     * Operation getUserPostsWithHttpInfo
     *
     * List posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: date, active, distance &lt;br /&gt;&lt;br /&gt; Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'date')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPosts'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\GetUserPosts200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function getUserPostsWithHttpInfo($user_id, $types, $sources, $sort_by = 'date', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['getUserPosts'][0])
    {
        $request = $this->getUserPostsRequest($user_id, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\GetUserPosts200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\GetUserPosts200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\GetUserPosts200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getUserPostsAsync
     *
     * List posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: date, active, distance &lt;br /&gt;&lt;br /&gt; Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'date')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPostsAsync($user_id, $types, $sources, $sort_by = 'date', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['getUserPosts'][0])
    {
        return $this->getUserPostsAsyncWithHttpInfo($user_id, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getUserPostsAsyncWithHttpInfo
     *
     * List posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: date, active, distance &lt;br /&gt;&lt;br /&gt; Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'date')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getUserPostsAsyncWithHttpInfo($user_id, $types, $sources, $sort_by = 'date', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['getUserPosts'][0])
    {
        $returnType = '\OpenAPI\Client\Model\GetUserPosts200Response';
        $request = $this->getUserPostsRequest($user_id, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getUserPosts'
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: date, active, distance &lt;br /&gt;&lt;br /&gt; Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'date')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getUserPostsRequest($user_id, $types, $sources, $sort_by = 'date', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['getUserPosts'][0])
    {

        // verify the required parameter 'user_id' is set
        if ($user_id === null || (is_array($user_id) && count($user_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_id when calling getUserPosts'
            );
        }

        // verify the required parameter 'types' is set
        if ($types === null || (is_array($types) && count($types) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $types when calling getUserPosts'
            );
        }

        // verify the required parameter 'sources' is set
        if ($sources === null || (is_array($sources) && count($sources) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sources when calling getUserPosts'
            );
        }



        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling UsersApi.getUserPosts, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling UsersApi.getUserPosts, must be bigger than or equal to 1.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling UsersApi.getUserPosts, must be bigger than or equal to 1.');
        }
        



        if ($radius !== null && $radius > 80500) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling UsersApi.getUserPosts, must be smaller than or equal to 80500.');
        }
        if ($radius !== null && $radius < 0) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling UsersApi.getUserPosts, must be bigger than or equal to 0.');
        }
        



        if ($include_reposts !== null && $include_reposts > 1) {
            throw new \InvalidArgumentException('invalid value for "$include_reposts" when calling UsersApi.getUserPosts, must be smaller than or equal to 1.');
        }
        if ($include_reposts !== null && $include_reposts < 0) {
            throw new \InvalidArgumentException('invalid value for "$include_reposts" when calling UsersApi.getUserPosts, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/users/{user_id}/posts';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $types,
            'types', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sources,
            'sources', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $group_ids,
            'group_ids', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $device_pixel_ratio,
            'device_pixel_ratio', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $latitude,
            'latitude', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $longitude,
            'longitude', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $radius,
            'radius', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_min,
            'date_min', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_max,
            'date_max', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $outcomes,
            'outcomes', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_reposts,
            'include_reposts', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($user_id !== null) {
            $resourcePath = str_replace(
                '{user_id}',
                ObjectSerializer::toPathValue($user_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchUserPosts
     *
     * Search posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $search The search query used to find posts. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: relevance, date, active, distance &lt;br /&gt;&lt;br /&gt; Relevance sorting will sort the posts that best match the search query first. Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'relevance')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserPosts'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OpenAPI\Client\Model\SearchUserPosts200Response
     */
    public function searchUserPosts($user_id, $search, $types, $sources, $sort_by = 'relevance', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['searchUserPosts'][0])
    {
        list($response) = $this->searchUserPostsWithHttpInfo($user_id, $search, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);
        return $response;
    }

    /**
     * Operation searchUserPostsWithHttpInfo
     *
     * Search posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $search The search query used to find posts. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: relevance, date, active, distance &lt;br /&gt;&lt;br /&gt; Relevance sorting will sort the posts that best match the search query first. Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'relevance')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserPosts'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OpenAPI\Client\Model\SearchUserPosts200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchUserPostsWithHttpInfo($user_id, $search, $types, $sources, $sort_by = 'relevance', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['searchUserPosts'][0])
    {
        $request = $this->searchUserPostsRequest($user_id, $search, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OpenAPI\Client\Model\SearchUserPosts200Response',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OpenAPI\Client\Model\SearchUserPosts200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\SearchUserPosts200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchUserPostsAsync
     *
     * Search posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $search The search query used to find posts. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: relevance, date, active, distance &lt;br /&gt;&lt;br /&gt; Relevance sorting will sort the posts that best match the search query first. Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'relevance')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchUserPostsAsync($user_id, $search, $types, $sources, $sort_by = 'relevance', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['searchUserPosts'][0])
    {
        return $this->searchUserPostsAsyncWithHttpInfo($user_id, $search, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchUserPostsAsyncWithHttpInfo
     *
     * Search posts by a user
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $search The search query used to find posts. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: relevance, date, active, distance &lt;br /&gt;&lt;br /&gt; Relevance sorting will sort the posts that best match the search query first. Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'relevance')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchUserPostsAsyncWithHttpInfo($user_id, $search, $types, $sources, $sort_by = 'relevance', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['searchUserPosts'][0])
    {
        $returnType = '\OpenAPI\Client\Model\SearchUserPosts200Response';
        $request = $this->searchUserPostsRequest($user_id, $search, $types, $sources, $sort_by, $group_ids, $per_page, $page, $device_pixel_ratio, $latitude, $longitude, $radius, $date_min, $date_max, $outcomes, $include_reposts, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchUserPosts'
     *
     * @param  string $user_id The user ID of the user whose posts will be retrieved. Using &#39;me&#39; as the user_id will return the posts for the current user. (required)
     * @param  string $search The search query used to find posts. (required)
     * @param  string $types A comma separated list of the post types to return.  The available post types are: offer, wanted, admin (required)
     * @param  string $sources A comma separated list of the post sources to retrieve posts from. The available sources are: groups, trashnothing, open_archive_groups. The trashnothing source is for public posts that are posted on Trash Nothing but are not associated with any group. The open_archive_groups source provides a way to easily request posts from groups that have open_archives set to true without having to pass a group_ids parameter.  When passed, it will automatically return posts from open archive groups that are within the area specified by the latitude, longitude and radius parameters (or all the open archive groups the requested user has posted to if latitude, longitude and radius aren&#39;t passed). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, passing the trashnothing source or the open_archive_groups source makes the latitude, longitude and radius parameters required. (required)
     * @param  string|null $sort_by How to sort the posts that are returned.  One of: relevance, date, active, distance &lt;br /&gt;&lt;br /&gt; Relevance sorting will sort the posts that best match the search query first. Date sorting will sort posts from newest to oldest. Active sorting will sort active posts before satisfied, withdrawn and expired posts and then sort by date. Distance sorting will sort the closest posts first. (optional, default to 'relevance')
     * @param  string|null $group_ids A comma separated list of the group IDs to retrieve posts from. This parameter is only used if the &#39;groups&#39; source is passed in the sources parameter and only groups that the current user is a member of or that are open archives groups will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br /&gt; NOTE: For requests using an api key instead of oauth, this field is required if the &#39;groups&#39; source is passed. In addition, only posts from groups that have open_archives set to true will be used (the group IDs of other groups will be silently discarded*). &lt;br /&gt;&lt;br/&gt; *To determine which group IDs were used and which were discarded, use the group_ids field in the response. (optional, default to 'The group IDs of every group the current user is a member of.')
     * @param  int|null $per_page The number of posts to return per page (must be &gt;&#x3D; 1 and &lt;&#x3D; 100). (optional, default to 20)
     * @param  int|null $page The page of posts to return. (optional, default to 1)
     * @param  float|null $device_pixel_ratio Client device pixel ratio used to determine thumbnail size (default 1.0). (optional, default to 1.0)
     * @param  float|null $latitude The latitude of a point around which to return posts. (optional)
     * @param  float|null $longitude The longitude of a point around which to return posts. (optional)
     * @param  float|null $radius The radius in meters of a circle centered at the point defined by the latitude and longitude parameters. When latitude, longitude and radius are passed, only posts within the circle defined by these parameters will be returned. (optional)
     * @param  \DateTime|null $date_min Only posts newer than or equal to this UTC date and time will be returned. (optional)
     * @param  \DateTime|null $date_max Only posts older than this UTC date and time will be returned. (optional)
     * @param  string|null $outcomes A comma separated list of the post outcomes to return.  The available post outcomes are: satisfied, withdrawn &lt;br /&gt;&lt;br /&gt; There are also a couple special values that can be passed.  If set to an empty string (the default), only posts that are not satisfied and not withdrawn and not expired are returned. If set to &#39;all&#39;, all posts will be returned no matter what outcome the posts have. If set to &#39;not-promised&#39;, only posts that are not satisfied ant not withdrawn and not expired and not promised are returned. (optional)
     * @param  int|null $include_reposts If set to 1 (the default), posts that are reposts will be included. If set to 0, reposts will be excluded. See the repost_count field of post objects for details about how reposts are identified. (optional, default to 1)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchUserPosts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchUserPostsRequest($user_id, $search, $types, $sources, $sort_by = 'relevance', $group_ids = 'The group IDs of every group the current user is a member of.', $per_page = 20, $page = 1, $device_pixel_ratio = 1.0, $latitude = null, $longitude = null, $radius = null, $date_min = null, $date_max = null, $outcomes = null, $include_reposts = 1, string $contentType = self::contentTypes['searchUserPosts'][0])
    {

        // verify the required parameter 'user_id' is set
        if ($user_id === null || (is_array($user_id) && count($user_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $user_id when calling searchUserPosts'
            );
        }

        // verify the required parameter 'search' is set
        if ($search === null || (is_array($search) && count($search) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search when calling searchUserPosts'
            );
        }

        // verify the required parameter 'types' is set
        if ($types === null || (is_array($types) && count($types) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $types when calling searchUserPosts'
            );
        }

        // verify the required parameter 'sources' is set
        if ($sources === null || (is_array($sources) && count($sources) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sources when calling searchUserPosts'
            );
        }



        if ($per_page !== null && $per_page > 100) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling UsersApi.searchUserPosts, must be smaller than or equal to 100.');
        }
        if ($per_page !== null && $per_page < 1) {
            throw new \InvalidArgumentException('invalid value for "$per_page" when calling UsersApi.searchUserPosts, must be bigger than or equal to 1.');
        }
        
        if ($page !== null && $page < 1) {
            throw new \InvalidArgumentException('invalid value for "$page" when calling UsersApi.searchUserPosts, must be bigger than or equal to 1.');
        }
        



        if ($radius !== null && $radius > 80500) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling UsersApi.searchUserPosts, must be smaller than or equal to 80500.');
        }
        if ($radius !== null && $radius < 0) {
            throw new \InvalidArgumentException('invalid value for "$radius" when calling UsersApi.searchUserPosts, must be bigger than or equal to 0.');
        }
        



        if ($include_reposts !== null && $include_reposts > 1) {
            throw new \InvalidArgumentException('invalid value for "$include_reposts" when calling UsersApi.searchUserPosts, must be smaller than or equal to 1.');
        }
        if ($include_reposts !== null && $include_reposts < 0) {
            throw new \InvalidArgumentException('invalid value for "$include_reposts" when calling UsersApi.searchUserPosts, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/users/{user_id}/posts/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sort_by', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $types,
            'types', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sources,
            'sources', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $group_ids,
            'group_ids', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $per_page,
            'per_page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $device_pixel_ratio,
            'device_pixel_ratio', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $latitude,
            'latitude', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $longitude,
            'longitude', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $radius,
            'radius', // param base name
            'number', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_min,
            'date_min', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $date_max,
            'date_max', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $outcomes,
            'outcomes', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $include_reposts,
            'include_reposts', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);


        // path params
        if ($user_id !== null) {
            $resourcePath = str_replace(
                '{user_id}',
                ObjectSerializer::toPathValue($user_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('api_key');
        if ($apiKey !== null) {
            $queryParams['api_key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
