#!/bin/bash
# shaped-ramp.sh - paces the SHAPED transport and ramps it back up.
#
# adaptive-shaper.sh decides WHO is throttling us and routes them through the
# shaped transport, which caps concurrency. That stops us hammering them but
# does nothing about burstiness: our mail is generated by cron jobs, so it
# arrives in slugs and leaves in slugs, and a slug is what providers punish.
# This adds the missing half - a paced send rate that starts slow and ratchets
# up while the shaped domains keep accepting.
#
# THE TRAP THIS AVOIDS: smtp_destination_rate_delay forces per-destination
# concurrency to 1, i.e. it SERIALISES. Gmail alone runs ~97k/day; paced at 2s
# that is 43k/day, so pacing it would build an unbounded backlog. So before
# pacing anything, check every shaped domain's actual daily volume against what
# the paced rate could carry, and refuse to pace if it would not fit.
set -u

# Single-instance. The state file is read at the top and written at the bottom,
# so two overlapping runs silently clobber each other: on 2026-08-20 a manual
# run raced the every-minute cron and the cron's stale copy reset the rung from
# 1 back to 0, which read exactly like an automatic ease-down that never
# happened.
LOCK=/var/lock/$(basename "$0").lock
exec 9>"$LOCK" || exit 0
flock -n 9 || exit 0
MAP=/etc/postfix/shaped_destinations
STATE=/var/lib/shaped-ramp/state
LOG=/var/log/shaped-ramp.log
MAILLOG=/var/log/mail.log
LADDER="30s 15s 8s 4s 2s 1s"
SAMPLE=200000

mkdir -p "$(dirname "$STATE")"
[ -f "$STATE" ] || echo "date= rung=0" > "$STATE"
# shellcheck disable=SC2046
eval $(cat "$STATE")
today=$(date -u +%F)

rung_delay() { n=$1; i=0; for d in $LADDER; do [ "$i" -eq "$n" ] && { echo "$d"; return; }; i=$((i+1)); done; echo "$d"; }
delay_secs() { echo "${1%s}"; }
cur_delay() { postconf -h shaped_destination_rate_delay 2>/dev/null; }
set_delay() {
  [ "$(cur_delay)" = "$1" ] && return
  postconf -e "shaped_destination_rate_delay=$1" && postfix reload >/dev/null 2>&1
  echo "$(date -u '+%F %H:%M')Z shaped rate_delay -> $1 (rung $rung)" >> "$LOG"
}

domains=$(awk 'NF {print $1}' "$MAP" 2>/dev/null)
if [ -z "$domains" ]; then
  set_delay 0s
  echo "date=$today rung=$rung" > "$STATE"
  exit 0
fi

want=$(rung_delay "$rung"); wsec=$(delay_secs "$want")
# Paced capacity per destination per HOUR, with concurrency forced to 1. Compare
# like with like: measure each domain's sends over the last hour, not over an
# arbitrary log sample.
cap_per_hour=$(( 3600 / wsec ))
hour_ago=$(date -u -d '60 min ago' '+%b %e %H:%M')

recent=$(tail -n "$SAMPLE" "$MAILLOG")
unfit=""
for d in $domains; do
  need=$(printf '%s\n' "$recent" | awk -v s="$hour_ago" '$0 >= s' | grep -c "to=<[^>]*@$d>.*status=sent")
  [ "$need" -gt "$cap_per_hour" ] && unfit="$unfit $d(${need}/h > ${cap_per_hour}/h)"
done

if [ -n "$unfit" ]; then
  set_delay 0s
  echo "$(date -u '+%F %H:%M')Z NOT pacing - would not carry the volume for:$unfit (concurrency cap only)" >> "$LOG"
else
  set_delay "$want"
fi

# Fast down / slow up. Ramping UP is a daily decision because acceptance has to
# be demonstrated over time; ramping DOWN must be immediate, because a provider
# refusing us now is refusing us now - holding the pace until midnight spends a
# whole day telling them we do not listen.
rs=$(printf '%s\n' "$recent" | awk -v s="$(date -u -d '10 min ago' '+%b %e %H:%M')" '$0 >= s' | grep -c "postfix-shaped.*status=sent")
rd=$(printf '%s\n' "$recent" | awk -v s="$(date -u -d '10 min ago' '+%b %e %H:%M')" '$0 >= s' | grep -c "postfix-shaped.*status=deferred")
if [ "$((rs + rd))" -ge 20 ] && [ "$rd" -gt "$rs" ] && [ "$rung" -gt 0 ]; then
  rung=$((rung - 1))
  set_delay "$(rung_delay "$rung")"
  echo "$(date -u '+%F %H:%M')Z refused now ($rs sent vs $rd deferred in 10m) - easing DOWN to rung $rung immediately" >> "$LOG"
  echo "date=$today rung=$rung" > "$STATE"
  exit 0
fi

# Daily roll: speed up while the shaped set is being accepted, slow down if not.
if [ "${date:-}" != "$today" ]; then
  sent=$(printf '%s\n' "$recent" | grep -c "postfix-shaped.*status=sent")
  def=$(printf '%s\n' "$recent" | grep -c "postfix-shaped.*status=deferred")
  if [ "$((sent + def))" -ge 100 ] && [ "$sent" -gt "$def" ]; then
    rung=$((rung + 1)); verdict="accepted ($sent sent vs $def deferred) - ramping UP to rung $rung"
  elif [ "$((sent + def))" -ge 100 ]; then
    rung=$(( rung > 0 ? rung - 1 : 0 )); verdict="still refused ($sent vs $def) - easing DOWN to rung $rung"
  else
    verdict="too few samples ($((sent + def))) - holding rung $rung"
  fi
  echo "$(date -u '+%F %H:%M')Z day rolled: $verdict" >> "$LOG"
fi
echo "date=$today rung=$rung" > "$STATE"
