<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Remove the group model.
 *
 * A post has one location and one moderation state, on `messages`. A member has one email
 * frequency, one posting status and one ban, on `users`. Communities, memberships and the
 * per-community copies of posts go. The only surviving use of a community is TrashNothing,
 * which addresses mail and members by community short name: `partner_areas` keeps the id,
 * short name and polygon of the communities that were syndicated, and nothing else reads it.
 *
 * Order: add, move data, then drop. Every step checks before it acts, so the migration can
 * be re-run after a partial failure. The production copy is the `_migration.sql` beside it.
 */
return new class extends Migration
{
    /** Tables that go entirely. Order matters where one references another. */
    private const DROP_TABLES = [
        'memberships_yahoo_dump', 'memberships_yahoo', 'memberships_history', 'memberships',
        'messages_groups',
        'groups_digests', 'groups_facebook_shares', 'groups_facebook_toshare', 'groups_facebook',
        'groups_images', 'groups_mods_welfare', 'groups_sponsorship', 'groups_twitter',
        'users_banned', 'communityevents_groups', 'volunteering_groups', 'partnerships_groups',
        'rippling_proximity_checked', 'rippling_proximity', 'mod_bulkops_run', 'plugin',
        // Word lists: the rules are questions a model answers now (see the judgement service).
        'concern_keywords', 'spam_keywords',
        'groups',
    ];

    /** [table, column] pairs that lose a column. */
    private const DROP_COLUMNS = [
        ['chat_rooms', 'groupid'], ['messages_spatial', 'groupid'], ['messages_drafts', 'groupid'],
        ['messages_postings', 'groupid'], ['messages_history', 'groupid'], ['messages_index', 'groupid'],
        ['messages_popular', 'groupid'], ['newsfeed', 'groupid'], ['logs', 'groupid'],
        ['users_comments', 'groupid'], ['users_modmails', 'groupid'], ['users_dashboard', 'groupid'],
        ['users_postnotifications_tracking', 'groupid'], ['alerts', 'groupid'], ['alerts_tracking', 'groupid'],
        ['admins', 'groupid'], ['polls', 'groupid'], ['shortlinks', 'groupid'], ['vouchers', 'groupid'],
        ['locations_excluded', 'groupid'], ['newsletters', 'groupid'], ['changes', 'groupid'],
        ['email_tracking', 'groupid'], ['stats', 'groupid'], ['stats_outcomes', 'groupid'],
        ['stats_summaries', 'groupid'], ['reengage', 'volunteer_groupid'],
        ['rippling_reach', 'rejected_groups'], ['rippling_reach', 'reachable_group_ids'],
        ['community_news_areas', 'anchorgroupid'], ['community_news_areas', 'groupids'],
        ['simulation_message_isochrones_messages', 'groupid'],
    ];

    /** Per-community statistics: meaningless nationally, regenerated by the batch. */
    private const TRUNCATE = ['stats', 'stats_outcomes', 'stats_summaries', 'users_dashboard'];

    public function up(): void
    {
        $this->addColumns();
        $this->moveData();
        $this->createPartnerAreas();
        $this->dropEverything();
    }

    private function addColumns(): void
    {
        Schema::table('users', function (Blueprint $table) {
            if (! Schema::hasColumn('users', 'emailfrequency')) {
                $table->integer('emailfrequency')->default(24)->comment('-1 immediate, 0 never, 24 daily');
            }
            if (! Schema::hasColumn('users', 'eventsallowed')) {
                $table->boolean('eventsallowed')->default(true);
            }
            if (! Schema::hasColumn('users', 'volunteeringallowed')) {
                $table->boolean('volunteeringallowed')->default(true);
            }
            if (! Schema::hasColumn('users', 'postingstatus')) {
                $table->enum('postingstatus', ['MODERATED', 'DEFAULT', 'PROHIBITED', 'UNMODERATED'])->nullable();
            }
            if (! Schema::hasColumn('users', 'banned')) {
                $table->timestamp('banned')->nullable()->index('banned');
            }
            if (! Schema::hasColumn('users', 'bannedby')) {
                $table->unsignedBigInteger('bannedby')->nullable();
            }
            if (! Schema::hasColumn('users', 'welcomed')) {
                $table->timestamp('welcomed')->nullable();
            }
            if (! Schema::hasColumn('users', 'modconfigid')) {
                $table->unsignedBigInteger('modconfigid')->nullable();
            }
            if (! Schema::hasColumn('users', 'reviewrequestedat')) {
                $table->timestamp('reviewrequestedat')->nullable()->index('reviewrequestedat');
            }
            if (! Schema::hasColumn('users', 'reviewreason')) {
                $table->string('reviewreason')->nullable();
            }
            if (! Schema::hasColumn('users', 'reviewedat')) {
                $table->timestamp('reviewedat')->nullable();
            }
        });

        Schema::table('messages', function (Blueprint $table) {
            if (! Schema::hasColumn('messages', 'collection')) {
                $table->enum('collection', ['Incoming', 'Pending', 'Approved', 'Spam', 'Rejected'])
                    ->default('Pending')->index('collection');
            }
            if (! Schema::hasColumn('messages', 'approvedby')) {
                $table->unsignedBigInteger('approvedby')->nullable();
            }
            if (! Schema::hasColumn('messages', 'approvedat')) {
                $table->timestamp('approvedat')->nullable();
            }
            if (! Schema::hasColumn('messages', 'rejectedat')) {
                $table->timestamp('rejectedat')->nullable();
            }
            if (! Schema::hasColumn('messages', 'autoreposts')) {
                $table->integer('autoreposts')->default(0);
            }
            if (! Schema::hasColumn('messages', 'lastautopostwarning')) {
                $table->timestamp('lastautopostwarning')->nullable();
            }
            if (! Schema::hasColumn('messages', 'lastchaseup')) {
                $table->timestamp('lastchaseup')->nullable();
            }
            if (! Schema::hasColumn('messages', 'contentcheck_checked_at')) {
                $table->timestamp('contentcheck_checked_at')->nullable();
            }
            if (! Schema::hasColumn('messages', 'contentcheck_reasons')) {
                $table->json('contentcheck_reasons')->nullable();
            }
        });

        if (Schema::hasTable('community_news_areas') && ! Schema::hasColumn('community_news_areas', 'authorityid')) {
            Schema::table('community_news_areas', function (Blueprint $table) {
                $table->unsignedBigInteger('authorityid')->nullable()->index('authorityid');
            });
        }
    }

    private function moveData(): void
    {
        if (Schema::hasTable('messages_groups')) {
            // The origin copy is the post's own moderation state; a rippled-in copy is a
            // reflection of it. QueuedUser and QueuedYahooUser were never-published states
            // from the old platform, so they fold into Pending.
            DB::statement("
                UPDATE messages m
                INNER JOIN messages_groups mg ON mg.msgid = m.id AND mg.groupid = (
                    SELECT x.groupid FROM messages_groups x WHERE x.msgid = m.id
                    ORDER BY x.rippled_in ASC, x.arrival ASC, x.groupid ASC LIMIT 1
                )
                SET m.collection = CASE mg.collection
                        WHEN 'Approved' THEN 'Approved'
                        WHEN 'Spam' THEN 'Spam'
                        WHEN 'Rejected' THEN 'Rejected'
                        WHEN 'Incoming' THEN 'Incoming'
                        ELSE 'Pending' END,
                    m.approvedby = mg.approvedby,
                    m.approvedat = mg.approvedat,
                    m.rejectedat = mg.rejectedat,
                    m.autoreposts = COALESCE(mg.autoreposts, 0),
                    m.lastautopostwarning = mg.lastautopostwarning,
                    m.lastchaseup = mg.lastchaseup,
                    m.contentcheck_checked_at = mg.contentcheck_checked_at,
                    m.contentcheck_reasons = mg.contentcheck_reasons,
                    m.heldby = COALESCE(m.heldby, mg.heldby),
                    m.spamtype = COALESCE(m.spamtype, mg.spamtype),
                    m.spamreason = COALESCE(m.spamreason, mg.spamreason)
            ");
        }

        if (Schema::hasTable('memberships')) {
            DB::statement("
                UPDATE users u
                INNER JOIN (
                    SELECT userid,
                        MIN(CASE WHEN emailfrequency = -1 THEN 0 WHEN emailfrequency > 0 THEN 1 ELSE 2 END) AS freqrank,
                        MAX(eventsallowed) AS eventsallowed,
                        MAX(volunteeringallowed) AS volunteeringallowed,
                        MAX(ourPostingStatus = 'PROHIBITED') AS prohibited,
                        MAX(ourPostingStatus = 'MODERATED') AS moderated,
                        MAX(ourPostingStatus = 'UNMODERATED') AS unmoderated,
                        MAX(ourPostingStatus = 'DEFAULT') AS dflt,
                        MAX(configid) AS configid
                    FROM memberships GROUP BY userid
                ) m ON m.userid = u.id
                SET u.emailfrequency = CASE m.freqrank WHEN 0 THEN -1 WHEN 1 THEN 24 ELSE 0 END,
                    u.eventsallowed = COALESCE(m.eventsallowed, 1),
                    u.volunteeringallowed = COALESCE(m.volunteeringallowed, 1),
                    u.postingstatus = CASE
                        WHEN m.prohibited = 1 THEN 'PROHIBITED'
                        WHEN m.moderated = 1 THEN 'MODERATED'
                        WHEN m.unmoderated = 1 THEN 'UNMODERATED'
                        WHEN m.dflt = 1 THEN 'DEFAULT'
                        ELSE NULL END,
                    u.modconfigid = m.configid
            ");
        }

        if (Schema::hasTable('users_banned')) {
            DB::statement("
                UPDATE users u
                INNER JOIN (SELECT userid, MIN(date) AS banned, MIN(byuser) AS bannedby FROM users_banned GROUP BY userid) b
                    ON b.userid = u.id
                SET u.banned = b.banned, u.bannedby = b.bannedby
                WHERE u.banned IS NULL
            ");
        }

        if (Schema::hasTable('memberships')) {
            // The member review flag was per membership; keep the most recent request and its reason.
            DB::statement(<<<'SQL'
                UPDATE users u
                INNER JOIN (
                    SELECT userid, MAX(reviewrequestedat) AS requestedat, MAX(reviewedat) AS reviewedat
                    FROM memberships WHERE reviewrequestedat IS NOT NULL GROUP BY userid
                ) m ON m.userid = u.id
                SET u.reviewrequestedat = m.requestedat,
                    u.reviewedat = m.reviewedat,
                    u.reviewreason = (SELECT x.reviewreason FROM memberships x
                                      WHERE x.userid = u.id AND x.reviewrequestedat = m.requestedat LIMIT 1)
            SQL);
        }
        DB::statement('UPDATE users SET welcomed = COALESCE(welcomed, added, NOW()) WHERE welcomed IS NULL');
    }

    private function createPartnerAreas(): void
    {
        if (Schema::hasTable('partner_areas') || ! Schema::hasTable('groups')) {
            return;
        }

        DB::statement("
            CREATE TABLE partner_areas (
                id BIGINT UNSIGNED NOT NULL PRIMARY KEY COMMENT 'The community id TrashNothing still sends',
                nameshort VARCHAR(80) NOT NULL,
                namefull VARCHAR(100) NULL,
                lat DECIMAL(10,6) NOT NULL,
                lng DECIMAL(10,6) NOT NULL,
                polyindex GEOMETRY NOT NULL SRID 3857,
                UNIQUE KEY nameshort (nameshort),
                SPATIAL INDEX polyindex (polyindex)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
              COMMENT='Areas TrashNothing addresses mail and members by. Nothing a member sees reads this.'
        ");

        DB::statement("
            INSERT INTO partner_areas (id, nameshort, namefull, lat, lng, polyindex)
            SELECT id, nameshort, namefull, COALESCE(lat, 0), COALESCE(lng, 0), polyindex
            FROM `groups`
            WHERE ontn = 1 AND polyindex IS NOT NULL
        ");
    }

    private function dropEverything(): void
    {
        foreach (self::TRUNCATE as $table) {
            if (Schema::hasTable($table)) {
                DB::table($table)->truncate();
            }
        }

        foreach (self::DROP_COLUMNS as [$table, $column]) {
            if (! Schema::hasTable($table) || ! Schema::hasColumn($table, $column)) {
                continue;
            }
            $this->dropForeignKeysOn($table, $column);
            $this->dropIndexesOn($table, $column);
            Schema::table($table, function (Blueprint $t) use ($column) {
                $t->dropColumn($column);
            });
        }

        foreach (self::DROP_TABLES as $table) {
            if (Schema::hasTable($table)) {
                $this->dropForeignKeysReferencing($table);
                Schema::drop($table);
            }
        }
    }

    /** Drop every foreign key on ($table.$column), by the name the database has for it. */
    private function dropForeignKeysOn(string $table, string $column): void
    {
        $names = DB::table('information_schema.KEY_COLUMN_USAGE')
            ->where('TABLE_SCHEMA', DB::getDatabaseName())
            ->where('TABLE_NAME', $table)
            ->where('COLUMN_NAME', $column)
            ->whereNotNull('REFERENCED_TABLE_NAME')
            ->pluck('CONSTRAINT_NAME')->unique();
        foreach ($names as $name) {
            DB::statement("ALTER TABLE `{$table}` DROP FOREIGN KEY `{$name}`");
        }
    }

    /** Drop every foreign key anywhere that references $table, so it can be dropped. */
    private function dropForeignKeysReferencing(string $table): void
    {
        $rows = DB::table('information_schema.KEY_COLUMN_USAGE')
            ->where('TABLE_SCHEMA', DB::getDatabaseName())
            ->where('REFERENCED_TABLE_NAME', $table)
            ->select('TABLE_NAME', 'CONSTRAINT_NAME')->distinct()->get();
        foreach ($rows as $row) {
            DB::statement("ALTER TABLE `{$row->TABLE_NAME}` DROP FOREIGN KEY `{$row->CONSTRAINT_NAME}`");
        }
    }

    /**
     * Drop a unique key that includes $column alongside other columns: once the column goes
     * it would collapse onto duplicates. Every other index loses the column automatically
     * when the column is dropped, and a non-unique one may be the index a foreign key needs,
     * so those are left alone.
     */
    private function dropIndexesOn(string $table, string $column): void
    {
        $indexes = DB::table('information_schema.STATISTICS')
            ->where('TABLE_SCHEMA', DB::getDatabaseName())
            ->where('TABLE_NAME', $table)
            ->where('INDEX_NAME', '!=', 'PRIMARY')
            ->where('NON_UNIQUE', 0)
            ->select('INDEX_NAME', 'COLUMN_NAME')->get()
            ->groupBy('INDEX_NAME');
        foreach ($indexes as $name => $columns) {
            $names = $columns->pluck('COLUMN_NAME')->all();
            if (count($names) > 1 && in_array($column, $names, true)) {
                DB::statement("ALTER TABLE `{$table}` DROP INDEX `{$name}`");
            }
        }
    }

    public function down(): void
    {
        // The community model cannot be rebuilt from what remains. Restore from backup.
    }
};
