check host iznik-server-go with address 127.0.0.1
  depends mysql
  start program = "/bin/bash -c 'cd /var/www/iznik-server-go; . ./.env ; nohup ./iznik-server-go >> /tmp/iznik-server-go.out 2>&1 &'"
  stop program = "/bin/bash -c '/bin/killall -SIGINT iznik-server-go; sleep 10; /bin/killall -9 iznik-server-go'"
  if failed port 8192 protocol http request "/api/group" timeout 10 seconds retry 10 then restart
  if 5 restarts within 5 cycles then timeout
