check process beanstalkd matching "beanstalkd"
   start program = "/usr/sbin/service beanstalkd start"
   stop program = "/usr/sbin/service beanstalkd stop"
   if failed port 11300 type tcp then alert

   if 5 restarts within 5 cycles then timeout
