# mysql
#
#check process mysqld with pidfile /var/run/mysqld/mysqld.pid
# group database
# start program = "/etc/init.d/mysql start" with timeout 900 seconds
# stop program = "/etc/init.d/mysql stop"
# if failed unixsocket /var/run/mysqld/mysqld.sock then restart
check process mysqld matching "mysqld"
  if failed unixsocket /var/run/mysqld/mysqld.sock then alert
  start program = "/usr/sbin/service mysql start" with timeout 900 seconds
  stop program = "/usr/sbin/service mysql stop" with timeout 900 seconds
check program mysql with path "/var/www/iznik/scripts/checkprimary"
  start program = "/usr/sbin/service mysql start" with timeout 900 seconds
  stop program = "/usr/sbin/service mysql stop" with timeout 900 seconds
  if status = 0 then restart
check program mysql_processes with path "/var/www/iznik/scripts/checkprocess"
  start program = "/usr/sbin/service mysql start" with timeout 900 seconds
  stop program = "/usr/sbin/service mysql stop" with timeout 900 seconds
  if status = 1 then restart

