check process php-fpm matching "php-fpm: master process .*/etc/php/8.1/fpm/php-fpm.conf"
    start program = "/usr/sbin/service php8.1-fpm start" with timeout 60 seconds
    stop program  = "/usr/sbin/service php8.1-fpm stop"
    if failed unixsocket /run/php/php8.1-fpm.sock with timeout 30 seconds for 3 cycles then restart
