check host iznik-spatial-go with address 127.0.0.1
  depends mysql
  start program = "/bin/bash -c 'cd /var/www/iznik-spatial-go; . ./.env ; nohup ./iznik-spatial-go >> /tmp/iznik-spatial-go.out 2>&1 &'"
  stop program = "/bin/bash -c '/bin/killall -SIGINT iznik-spatial-go; sleep 10; /bin/killall -9 iznik-spatial-go'"
  if failed port 8194 protocol http request "/health" timeout 10 seconds retry 10 then restart
  if 5 restarts within 5 cycles then timeout
